/* 
between 100-1000
My Score 819 minimum 720
A company has an ecommerce application that stores inventory data in an Amazon DynamoDB table. Occasionally during price updates, some items are updated concurrently. This process generates some prices that are different from the prices that the company intended.
Which DynamoDB feature should a developer use to enforce consistency in the price update process? I put Batch (wrong)
Conditional writes are helpful when you want to ensure that an update succeeds only if an item currently has a specific value.
=============
A development team uses an Amazon DynamoDB table as part of a data collection project. The average table item is 7 KB in size. The table experiences no more than 100 reads and 50 writes each second. The table has no local secondary indexes. Eventually consistent reads are acceptable.

What are the minimum acceptable values for the table's read capacity units (RCU) and write capacity units (WCU)?
Correct. To calculate RCU:

Each RCU can read up to 4 KB on a strongly consistent basis.
Each 7 KB item requires 2 RCU for each read. (Round 7 up to the next multiple of 4, then divide by 4 = 2.)
100 such items × 2 = 200.
Eventually consistent reads require only 50% = 100 RCU.
To calculate WCU:

Each WCU can write up to 1 KB.
Each 7 KB item requires 7 WCU for each write.
50 such items × 7 = 350 WCU.
==============
Correct. Lambda functions automatically store logs generated by code in CloudWatch Logs. However, the Lambda functions require the execution role to be configured with the appropriate permissions.
==============
A custom CodeBuild image is a Docker image that you create with everything you need to build and test a project. When a developer builds the application, CodeBuild will retrieve the Docker image from the container registry that the project configuration specifies. CodeBuild will use the environment to compile source code, run tests, and package an application. There is no need to download the packages from anywhere upon each build. This solution greatly reduces the build time.
====================
Move Static Content to S3. This process reduces the load on the web server and removes the need to store static content on each horizontally scaled instance.
====================
Correct. An Amazon Simple Queue Service (Amazon SQS) dead-letter queue offers message durability and can store unsuccessful Lambda events for processing later.
====================
Correct. Social IdPs are based on OpenID. All OpenID providers require the client application to register. The results of registration are an app client ID and an app client secret. 
====================
A development team uses AWS CodeDeploy to deploy software changes to Amazon EC2 instances. The deployments begin to fail. The team traces the problem to a specific EC2 instance. The CodeDeploy agent's log file contains the following error message:

InvalidSignatureException – Signature expired: [time] is now earlier than [time]

What is the underlying cause of this issue?
I thought (did not finish in the specified time, wrong)
CodeDeploy requires accurate time references to perform its operations. If the date and time on the instance are not set correctly, the date and time might not match the signature timestamp of the deployment request, which CodeDeploy rejects.
====================
A company is storing its application logs in Amazon CloudWatch Logs. The logs must be encrypted at rest by an AWS Key Management Service (AWS KMS) customer managed key. A developer is working on an application that is in violation of this requirement.

What should the developer do to comply with this requirement?
I thought delete in the console (You cannot use the console to encrypt CloudWatch Logs log groups with a customer managed key. )
To use a customer managed key, you must encrypt CloudWatch Logs log groups by using the AWS CLI. Additionally, the customer managed key must be a symmetric key.
====================
Correct. A ProvisionedThroughputExceededException error indicates that the maximum allowed provisioned throughput for a table, or for one or more global secondary indexes, has been exceeded.
====================
Correct. For applications that run on EC2 instances, AWS recommends the use of temporary credentials through IAM roles. You can configure the IAM roles for an EC2 Auto Scaling group through the launch template.
====================
Correct. You can use Amazon S3 to circumvent the 50 MB deployment package size limit. The Amazon S3 upload method provides a documented best practice workaround for the 50 MB file size quota.
----Although you can use a Lambda layer to shrink the deployment package size, you would need to take an additional step to create the layer and reference the layer through the --layers CLI parameter. However, the answer choice does not specify these additional steps.
====================
Correct. The file size exceeded the maximum upload size limit for a single put operation. You can use multipart uploads in Amazon S3 to upload larger files.
====================
A development team runs an extensive set of automated tests by using an AWS CodeBuild action in an AWS CodePipeline test stage. The tests take 30 minutes to run for each build. The team wants to reduce the time necessary to run the tests by conducting multiple tests in parallel. To accomplish this goal, the team breaks the test into multiple independent segments.

Which solution will meet these requirements?
I thought multi parallel pipeline stages (CodePipeline stages run sequentially. Only actions within the same CodePipeline stage can run in parallel)
CodeBuild can run test actions. A single CodePipeline stage can run many CodeBuild actions in parallel.
====================
Correct. The API Gateway IntegrationLatency metric denotes the time between when API Gateway relays a request to the backend and when it receives a response from the backend. The IntegrationLatency metric would help to diagnose the issue.
====================
Correct. If you deny an "aws:SecureTransport": "false" condition, you will not allow any attempts to connect to the S3 bucket through HTTP, even if other policies allow such connections.
====================
Correct. A global secondary index efficiently retrieves the leaderboard. You can create a global secondary index named leaderboard, with a partition key of sport_name and a sort key of score. The base table's primary key attributes are always projected into an index, so the user_id attribute is also present. Additionally, you can create a global secondary index after the table is already created.
====================
Correct. A VPC-connected Lambda function has the capability to query the EC2 instances directly and check the application-specific status. You can invoke Lambda functions on a schedule by using EventBridge.
====================
A development team at an ecommerce company uses an Amazon Simple Queue Service (Amazon SQS) queue to store submitted orders. The team writes an application that runs on Amazon EC2 instances. The application reads orders from the SQS queue and writes the data to a relational database. Cases of duplicate orders are discovered daily in the database.

Which actions will resolve the issue with duplicate orders? (Select TWO.)
If the visibility timeout expires before the message is processed and deleted, another consumer could retrieve the message and process it again. This process would create duplicate information on the database. To prevent the duplications, AWS recommends setting the visibility timeout to a safe threshold, which is the maximum time that it takes the application to process and delete a message from the queue. 
And
Developers should design each application so that it does not create duplicates when processing the same message more than once. In this case, the database could be checked to see if another order for the same amount was already sent by a customer on the same day. If there is another order, ignore it or delete the duplicate.
====================
Correct. Amazon Cognito Sync is an AWS service that gives developers the ability to synchronize user profile data across mobile devices and the web.
====================
Correct. The Amazon S3 encryption client cannot decrypt data that the Encryption SDK has encrypted. You must use the Encryption SDK for both encryption and decryption operations, or you must use S3 client-side encryption/the S3 encryption client for both encryption and decryption operations.
====================
Correct. You can use Amazon Cognito to identify users at scale. You can grant access to DynamoDB by using an identity credential provided by Amazon Cognito.
====================
Correct. You can create a new environment and perform an environment swap (blue/green deployment) to meet the requirements. A Blue/Green deployment policy is the ideal deployment policy because of the minimal downtime and the option to run and switch between application versions.
====================
Correct. Lambda layers allow developers to share prerequisites such as libraries, custom runtimes, data, or configuration files. Layers also promote code sharing and faster iteration of Lambda code.
====================
Correct. The AccessDenied error occurs when the Lambda function's execution role does not have appropriate DynamoDB write permissions. To resolve this error, you can adjust the policy to include the appropriate write permissions for DynamoDB. The AccessDeniedException generates the following message: Access denied.
====================
Correct. To create a Lambda function with a Java Implementation, you first create a Lambda function deployment package. This deployment package is a .zip or .jar file consisting of your code and any dependencies.
====================
A company is building a cloud solution to analyze customer demographic data. The data includes personally identifiable information (PII) such as full names, street addresses, and financial records.

A developer is configuring a source Amazon DynamoDB table with a DynamoDB stream. The developer is writing an AWS Lambda function that will ingest the demographic data from the DynamoDB stream, perform analytics, and write results to a separate DynamoDB table. The application must log important AWS API workflow events for monitoring purposes, but the application must not expose the PII.

Which combination of actions should the developer take to log the LARGEST amount of AWS API operational information in the application without exposing the PII? (Select TWO.)
I thought ( NEW_IMAGE, but the entire database item, including PII. A log of this event would expose the PII.)
KEYS_ONLY events record only the partition and sort keys of changed DynamoDB items.
A log that includes KEYS_ONLY events will not expose any PII. This solution is an effective component of workflow event logs. A log of only the API response metadata will not expose customer PII. This solution exposes only the metadata about the specific API request.
=====================
Correct. Amazon SNS can be used as part of an event-driven, serverless application. Additionally, a Lambda function can subscribe to an Amazon SNS topic.
=====================
Correct. You can use the CloudWatch agent to collect logs from EC2 instances and on-premises servers. You can use the CloudWatch console to view CloudWatch logs and graph metrics that are created by using metric filters.
=====================
Correct. DynamoDB Streams captures a time-ordered sequence of item-level modifications in any DynamoDB table. DynamoDB Streams stores this information in a log for up to 24 hours. Applications can access this log and view the data items as the items appeared before and after they were modified in near real time (NRT). A Lambda function is a serverless solution to send messages from a DynamoDB stream.
=====================
Correct. DynamoDB can serve as a simple table structure. You can establish a DynamoDB stream on a table to capture changes that are made in the table. Lambda functions can use DynamoDB streams as an event source. Any Lambda function can contain code to send a notification to an SNS topic.
=====================
Correct. Configuration files in the .ebextensions folder should be saved with the .config extension. After the change is deployed, the application performs health checks by using the /health_check URL.
=====================
Correct. Rolling deployment splits the instances into batches and deploys one batch at a time. Rolling deployment does not initiate a new service. Rolling deployment continues sending requests. However, you can experience an outage in the service.
=====================
Correct. Each PutRecords API call can support many records, up to a size limit for the entire request. This support greatly increases throughput.
=====================
Correct. DynamoDB provides predictable read performance when you provide a partition key. Eventually consistent reads consume the fewest RCUs. Eventually consistent reads are safe to use because the microservice can tolerate stale data.
=====================
A website allows users to upload photos to Amazon S3. An S3 event invokes an AWS Lambda function that uses the Amazon Rekognition DetectLabels operation to detect real-world objects within a photo. The website needs to store this data in a search index to allow users to quickly locate all photos associated with a label.

Which solution will meet these requirements?
I thought use object tags (Many AWS resources support the concept of tags. You can use tags can to manage, identify, organize, search for, and filter resources. However, the describe-tags API reports only EC2 instance tags and does not support indexing.)
Answer: insert an item foe each s3 key, label, and user combo into a dynamodb table, create a global sec index with username as pk, label as sort key. call queryitem API on index to find all objects that share the username and label value. 
 A DynamoDB table that is keyed by S3 object key, label, and user would allow you to store every unique label combination for every object for every user. The global secondary index that is keyed by user and label provides an alternate organization for fast lookup performance. The key values in a global secondary index do not need to be unique. The QueryItem API can quickly look up all items for a user, including all labels and all S3 objects for each label.
======================
Correct. Client-side encryption with customer-managed encryption keys allows you to select either symmetric or asymmetric keys.
======================
Correct. The most likely cause is an incorrectly configured ALB Availability Zone because the instances are registered. You can enable and disable Availability Zones at any time. After you enable an Availability Zone, the load balancer starts routing requests to the registered targets in that Availability Zone. This process should resolve the issue.
======================
A developer deploys a custom application to three Amazon EC2 instances. The application processes messages from an Amazon Simple Queue Service (Amazon SQS) standard queue with default settings. When the developer runs a load test on the Amazon SQS queue, the developer discovers that the application processes many messages multiple times.

How can the developer ensure that the application processes each message exactly once?
I thought modify to the FIFO but (You cannot change the queue type after you create the queue.)
SQS FIFO queues support exactly-once processing semantics.
=====================
A new mobile app uses Amazon Cognito web identity federation. Immediately after a user logs in, the following error occurs:

AccessDenied -- Not authorized to perform sts:AssumeRoleWithWebIdentity

A developer determines that the Amazon Cognito configuration appears to be correct.

Which of the following could be the cause of the error?
I thought incorrect access policy but (The error indicates that the app did not allow the user to assume the role. This denial involves the trust policy. If the error were related to the access policy, the error would occur when the user attempted to log in by using the provided credentials for the role. An access policy error would not indicate AWS Security Token Service (AWS STS).)
The dev incorrectly defined the authenticated principal role trust policy.
The trust policy likely does not contain the proper principal, action, or condition to fully grant access to the role to the user.
=====================
A development team uses AWS CodeBuild to build an application. The developers observe that downloads of large dependency files consume most of the time on each build. The downloaded dependency files are stored in a /.m2 folder. The builds are run frequently.


Which set of actions would MOST improve build performance?
I thought shared codebuile proj, call putresourcepolicy api to include as shared resource but (Incorrect. A shared CodeBuild project is accessible to other AWS accounts and users. The PutResourcePolicy API allows an owner to designate the principals with whom the project is shared. A shared CodeBuild project does not cache or pre-download any resources. For this reason, it will not improve the build performance.)
Implement local caching, modify buildspec cache settings to include a path to /.m2 folder.
Correct. A cache can store reusable pieces of your build environment and use them across multiple builds. Local caching stores a cache on a build host. When dependency files are large or builds are frequent, local caching helps to avoid large, repetitive downloads that can slow builds.
=====================
Correct. You can use provisioned concurrency to initialize the SDK clients and database connections outside of the function handler. This solution will prepare the connections to respond immediately to the function's invocations. This solution reduces the time to API Gateway and reduces the Lambda function integration latency.
=====================
Correct. Secrets Manager can store and distribute credentials programmatically from a central and secure datastore. Secrets Manager can also automatically rotate the secrets according to a specified schedule.
=====================
Correct. Valid CodePipeline action types are source, build, test, deploy, approval, and invoke. An approval action is the most appropriate way to accomplish the requirements.
=====================
Correct. An SQS queue can be established as a dead-letter queue associated with an SNS subscription. Any delivery failures are stored on this queue.
=====================
Correct. Secrets Manager can store secrets that AWS KMS encrypts at rest. Secrets Manager also supports the automatic rotation of database credentials. You can use IAM permissions to control access to the secret value of the database credentials.
=====================
Correct. This solution requires the least amount of development effort. You can manage the rotation schedule in Secrets Manager. You must update the API and Lambda functions with a single API call to pull the secret from Secrets Manager. Secrets Manager is the most suitable solution because it is designed for secrets. Secrets Manager turns on encryption by default, and you cannot turn off the encryption. Secrets Manager can automatically handle secret rotation.
=====================
Correct. In a process known as attribute-based access control, the principal's attributes from the user pool are used to allow or deny access to resources based on matching attributes. A single IAM role on the identity pool achieves this attribute-based access control. The user pool requires no information about roles, only a department attribute.
=====================
Correct. You can use S3 Event Notifications to invoke a Lambda function upon a specific S3 event such as a Put or Delete operation.
=====================
Correct. API Gateway stages define stage variables. The variables can have different values for different stages. Integration requests define API Gateway resource/method integrations, including Lambda functions. Lambda function references can include dynamic references to stage variables.
=====================
Correct. X-Ray gives you the ability to trace latency issues with your API Gateway APIs. X-Ray provides an end-to-end view of requests as they travel through your application. X-Ray can be used to trace and analyze user requests. These collected traces give you the ability to evaluate the end-to-end latency and identify performance bottlenecks.
=====================
Correct. API caching in API Gateway improves performance by reducing the number of requests that are sent to your endpoint service.
=====================
Correct. You can automate the whole code release process by using CodePipeline. CodeCommit is a version control repository that can store and manage source code. You can use CodeBuild to test code and run builds. CodeDeploy's blue/green deployment type gives you the ability to verify a new deployment of a service before you send production traffic to the deployment.
=====================
Correct. Lambda function versions give you the ability to specify different function code, dependencies, and settings such as environment variables. This solution gives you the ability to create a separate set of frontend components for the test environment.
=====================
Correct. X-Ray is a distributed tracing service that identifies issues and opportunities for optimization in an application where a user request is made across services. X-Ray requires a container to collect tracing data from Amazon ECS.
=====================
Correct. The GetId API is called with an OpenId token from a web identity provider and returns an Amazon Cognito ID. The GetCredentialsForIdentity API is called with an Amazon Cognito ID and returns temporary credentials. This flow is known as "enhanced (simplified) authflow," and it presumes that the identity pool, IAM roles, and external identity providers have all been configured.
=====================
Correct. Certain AWS operations return an encoded authorization message. When you receive an encoded message, the AWS STS decode-authorization-message command can help you decode additional information about the authorization status of a request from an encoded message that is returned in response to an AWS request.
=====================
Correct. The CodeBuild buildspec.yml file and the CodeDeploy appspec.yml file should be in the root of the source directory.
=====================
Correct. ACM can give you the ability to create, store, and renew the public and private SSL/TLS X.509 certificates and keys that protect many AWS websites and applications. You can configure the certificates for use with an ALB.
=====================
Correct. An increase in memory size also increases CPU available to your function.
=====================
Correct. You can use Step Functions to create complex workflows, including tasks that invoke Lambda functions. Standard workflows can be long-lived and can include tasks with retriers that retry a failed task. You can start a state machine from API Gateway REST API by using the POST method.
=====================
Correct. You can use X-Ray to trace the DynamoDB API call from a Lambda function. This solution helps identify performance bottlenecks and facilitate troubleshooting.
=====================
A gaming company maintains a website that must display a list of the top 10 highest scores for a game. The company stores the top 10 list in Amazon DynamoDB. Users who access this page are not authenticated. The company must use the AWS SDK for JavaScript in the Browser to make the DynamoDB API call.

Which solution is the MOST secure way to meet these requirements?
I thougth the answer was "create an IAM Role, store the ARN of the role in the website, use the ARN to call STS Assumerole." But the AssumeRole API requires AWS security credentials and a role ARN is not a security credential.
So the answer was create an IAM Role and cognito identity pool, associate the role with unauthenticated identities. Then create a DynamoDB table client object with the temporary credentials from the AWS.CognitoIdentityCrentials object. 

=================
Correct. The GetObject API call must specify the customer-provided encryption key that is used to initially encrypt the data


=================
A company is migrating a legacy application to Amazon EC2 instances. The application uses a user name and password that are stored in the source code to connect to a MySQL database. The company will migrate the database to an Amazon RDS for MySQL DB instance. As part of the migration, the company needs to implement a secure way to store and automatically rotate the database credentials.
Secrets Manager.

======================
A developer is creating a web application that must give users the ability to post comments and receive feedback in near real time.
A) Create an AWS AppSync schema and corresponding APIs. Use an Amazon DynamoDB table as the data store.
B) Create a WebSocket API in Amazon API Gateway. Use an AWS Lambda function as the backend. Use an Amazon DynamoDB table as the data store.

*/